import React, { useState } from 'react';
import { FileText, Download, Upload, Search, X, File, Folder, ChevronRight, ArrowLeft } from 'lucide-react';
import { useData } from '../context/DataContext';
import { useAuth } from '../context/AuthContext';
import type { Note } from '../types';
import { motion, AnimatePresence } from 'framer-motion';

const Notes = () => {
    const { notes, addNote, courses } = useData();
    const { user } = useAuth();
    const [isUploadModalOpen, setIsUploadModalOpen] = useState(false);
    const [searchQuery, setSearchQuery] = useState('');

    // Upload state
    const [uploadTitle, setUploadTitle] = useState('');
    const [uploadCourseId, setUploadCourseId] = useState('');
    const [uploadUnit, setUploadUnit] = useState('');
    const [isUploading, setIsUploading] = useState(false);

    // Navigation state
    const [currentView, setCurrentView] = useState<'subjects' | 'units' | 'notes'>('subjects');
    const [selectedSubject, setSelectedSubject] = useState<string | null>(null);
    const [selectedUnit, setSelectedUnit] = useState<string | null>(null);

    // Get unique subjects
    const subjects = Array.from(new Set(notes.map(note => note.courseName)));

    // Get units for selected subject
    const getUnitsForSubject = (subject: string) => {
        const subjectNotes = notes.filter(note => note.courseName === subject);
        return Array.from(new Set(subjectNotes.map(note => note.unit || 'General')));
    };

    // Get notes for selected unit
    const getNotesForUnit = (subject: string, unit: string) => {
        return notes.filter(note =>
            note.courseName === subject &&
            (note.unit || 'General') === unit &&
            (note.title.toLowerCase().includes(searchQuery.toLowerCase()) ||
                note.courseName.toLowerCase().includes(searchQuery.toLowerCase()))
        );
    };

    const handleUpload = async (e: React.FormEvent) => {
        e.preventDefault();
        if (!user || !uploadCourseId) return;

        setIsUploading(true);
        try {
            const selectedCourse = courses.find(c => c.id === uploadCourseId);

            const newNote: Note = {
                id: '', // Will be generated by DB
                title: uploadTitle,
                courseId: uploadCourseId,
                courseName: selectedCourse?.name || '',
                author: user.name,
                date: new Date().toISOString().split('T')[0],
                url: '#', // Mock URL for now
                type: 'PDF',
                size: '1.2 MB', // Mock size
                unit: uploadUnit || 'General',
            };

            await addNote(newNote);
            setIsUploadModalOpen(false);
            setUploadTitle('');
            setUploadCourseId('');
            setUploadUnit('');
        } catch (error) {
            console.error('Error uploading note:', error);
            alert('Failed to upload note');
        } finally {
            setIsUploading(false);
        }
    };

    const navigateBack = () => {
        if (currentView === 'notes') {
            setCurrentView('units');
            setSelectedUnit(null);
        } else if (currentView === 'units') {
            setCurrentView('subjects');
            setSelectedSubject(null);
        }
    };

    return (
        <div className="space-y-6">
            <div className="flex items-center justify-between">
                <div className="flex items-center gap-2">
                    {currentView !== 'subjects' && (
                        <button
                            onClick={navigateBack}
                            className="rounded-full p-2 hover:bg-gray-100 dark:hover:bg-surface-800"
                        >
                            <ArrowLeft className="h-5 w-5 text-gray-500 dark:text-gray-400" />
                        </button>
                    )}
                    <div>
                        <h1 className="text-2xl font-bold text-gray-900 dark:text-white">Study Notes</h1>
                        <div className="flex items-center gap-2 text-sm text-gray-500 dark:text-gray-400">
                            <span>Subjects</span>
                            {selectedSubject && (
                                <>
                                    <ChevronRight className="h-4 w-4" />
                                    <span>{selectedSubject}</span>
                                </>
                            )}
                            {selectedUnit && (
                                <>
                                    <ChevronRight className="h-4 w-4" />
                                    <span>{selectedUnit}</span>
                                </>
                            )}
                        </div>
                    </div>
                </div>
                <button
                    onClick={() => setIsUploadModalOpen(true)}
                    className="flex items-center gap-2 rounded-lg bg-primary-600 px-4 py-2 text-sm font-medium text-white hover:bg-primary-700 transition-colors"
                >
                    <Upload className="h-4 w-4" />
                    Upload Note
                </button>
            </div>

            {currentView === 'notes' && (
                <div className="relative">
                    <Search className="absolute left-3 top-1/2 h-5 w-5 -translate-y-1/2 text-gray-400" />
                    <input
                        type="text"
                        placeholder="Search notes..."
                        value={searchQuery}
                        onChange={(e) => setSearchQuery(e.target.value)}
                        className="h-11 w-full rounded-xl border border-gray-200 bg-white pl-10 pr-4 text-sm outline-none focus:border-primary-500 focus:ring-1 focus:ring-primary-500 dark:bg-surface-900 dark:border-white/10 dark:text-white"
                    />
                </div>
            )}

            <AnimatePresence mode="wait">
                {currentView === 'subjects' && (
                    <motion.div
                        initial={{ opacity: 0, x: -20 }}
                        animate={{ opacity: 1, x: 0 }}
                        exit={{ opacity: 0, x: 20 }}
                        className="grid gap-4 md:grid-cols-2 lg:grid-cols-3"
                    >
                        {subjects.map((subject) => (
                            <div
                                key={subject}
                                onClick={() => {
                                    setSelectedSubject(subject);
                                    setCurrentView('units');
                                }}
                                className="group cursor-pointer rounded-xl border border-gray-200 bg-white p-6 shadow-sm transition-all hover:shadow-md hover:border-primary-500 dark:bg-surface-900 dark:border-white/10"
                            >
                                <div className="flex items-center gap-4">
                                    <div className="rounded-lg bg-blue-100 p-3 text-blue-600 dark:bg-blue-900/30 dark:text-blue-400">
                                        <Folder className="h-8 w-8" />
                                    </div>
                                    <div>
                                        <h3 className="font-bold text-gray-900 dark:text-white">{subject}</h3>
                                        <p className="text-sm text-gray-500 dark:text-gray-400">{getUnitsForSubject(subject).length} Units</p>
                                    </div>
                                </div>
                            </div>
                        ))}
                    </motion.div>
                )}

                {currentView === 'units' && selectedSubject && (
                    <motion.div
                        initial={{ opacity: 0, x: -20 }}
                        animate={{ opacity: 1, x: 0 }}
                        exit={{ opacity: 0, x: 20 }}
                        className="grid gap-4 md:grid-cols-2 lg:grid-cols-3"
                    >
                        {getUnitsForSubject(selectedSubject).map((unit) => (
                            <div
                                key={unit}
                                onClick={() => {
                                    setSelectedUnit(unit);
                                    setCurrentView('notes');
                                }}
                                className="group cursor-pointer rounded-xl border border-gray-200 bg-white p-6 shadow-sm transition-all hover:shadow-md hover:border-primary-500 dark:bg-surface-900 dark:border-white/10"
                            >
                                <div className="flex items-center gap-4">
                                    <div className="rounded-lg bg-purple-100 p-3 text-purple-600 dark:bg-purple-900/30 dark:text-purple-400">
                                        <Folder className="h-8 w-8" />
                                    </div>
                                    <div>
                                        <h3 className="font-bold text-gray-900 dark:text-white">{unit}</h3>
                                        <p className="text-sm text-gray-500 dark:text-gray-400">
                                            {getNotesForUnit(selectedSubject, unit).length} Notes
                                        </p>
                                    </div>
                                </div>
                            </div>
                        ))}
                    </motion.div>
                )}

                {currentView === 'notes' && selectedSubject && selectedUnit && (
                    <motion.div
                        initial={{ opacity: 0, x: -20 }}
                        animate={{ opacity: 1, x: 0 }}
                        exit={{ opacity: 0, x: 20 }}
                        className="grid gap-4 md:grid-cols-2 lg:grid-cols-3"
                    >
                        {getNotesForUnit(selectedSubject, selectedUnit).map((note) => (
                            <div key={note.id} className="flex flex-col justify-between rounded-xl border border-gray-200 bg-white p-5 shadow-sm transition-all hover:shadow-md dark:bg-surface-900 dark:border-white/10">
                                <div>
                                    <div className="flex items-start justify-between">
                                        <div className="rounded-lg bg-gray-100 p-2 dark:bg-surface-800">
                                            <FileText className="h-6 w-6 text-gray-600 dark:text-gray-300" />
                                        </div>
                                        <span className="rounded-full bg-gray-100 px-2.5 py-0.5 text-xs font-medium text-gray-600 dark:bg-surface-800 dark:text-gray-300">
                                            {note.type}
                                        </span>
                                    </div>
                                    <div className="mt-4">
                                        <h3 className="font-semibold text-gray-900 dark:text-white line-clamp-1">{note.title}</h3>
                                        <p className="text-sm text-gray-500 dark:text-gray-400">{note.courseName}</p>
                                    </div>
                                </div>

                                <div className="mt-4 flex items-center justify-between border-t border-gray-100 pt-4 dark:border-white/10">
                                    <div className="text-xs text-gray-500 dark:text-gray-400">
                                        <p>{note.author}</p>
                                        <p>{note.date}</p>
                                    </div>
                                    <button className="rounded-lg p-2 text-gray-500 hover:bg-gray-100 hover:text-primary-600 transition-colors dark:text-gray-400 dark:hover:bg-surface-800 dark:hover:text-primary-400">
                                        <Download className="h-5 w-5" />
                                    </button>
                                </div>
                            </div>
                        ))}
                    </motion.div>
                )}
            </AnimatePresence>

            {isUploadModalOpen && (
                <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 backdrop-blur-sm">
                    <div className="w-full max-w-md rounded-2xl bg-white p-6 shadow-xl dark:bg-surface-900">
                        <div className="flex items-center justify-between mb-6">
                            <h2 className="text-lg font-bold text-gray-900 dark:text-white">Upload Note</h2>
                            <button
                                onClick={() => setIsUploadModalOpen(false)}
                                className="rounded-full p-1 text-gray-400 hover:bg-gray-100 hover:text-gray-600 dark:hover:bg-surface-800"
                            >
                                <X className="h-5 w-5" />
                            </button>
                        </div>

                        <form onSubmit={handleUpload} className="space-y-4">
                            <div>
                                <label className="mb-1 block text-sm font-medium text-gray-700 dark:text-gray-300">Title</label>
                                <input
                                    type="text"
                                    value={uploadTitle}
                                    onChange={(e) => setUploadTitle(e.target.value)}
                                    className="w-full rounded-lg border border-gray-300 px-3 py-2 text-sm outline-none focus:border-primary-500 focus:ring-1 focus:ring-primary-500 dark:bg-surface-800 dark:border-white/10 dark:text-white"
                                    placeholder="e.g. Chapter 1 Summary"
                                    required
                                />
                            </div>

                            <div>
                                <label className="mb-1 block text-sm font-medium text-gray-700 dark:text-gray-300">Course</label>
                                <select
                                    value={uploadCourseId}
                                    onChange={(e) => setUploadCourseId(e.target.value)}
                                    className="w-full rounded-lg border border-gray-300 px-3 py-2 text-sm outline-none focus:border-primary-500 focus:ring-1 focus:ring-primary-500 dark:bg-surface-800 dark:border-white/10 dark:text-white"
                                    required
                                >
                                    <option value="">Select Course</option>
                                    {courses.map(course => (
                                        <option key={course.id} value={course.id}>{course.name}</option>
                                    ))}
                                </select>
                            </div>

                            <div>
                                <label className="mb-1 block text-sm font-medium text-gray-700 dark:text-gray-300">Unit</label>
                                <select
                                    value={uploadUnit}
                                    onChange={(e) => setUploadUnit(e.target.value)}
                                    className="w-full rounded-lg border border-gray-300 px-3 py-2 text-sm outline-none focus:border-primary-500 focus:ring-1 focus:ring-primary-500 dark:bg-surface-800 dark:border-white/10 dark:text-white"
                                    required
                                >
                                    <option value="">Select Unit</option>
                                    <option value="Unit 1">Unit 1</option>
                                    <option value="Unit 2">Unit 2</option>
                                    <option value="Unit 3">Unit 3</option>
                                    <option value="Unit 4">Unit 4</option>
                                    <option value="Unit 5">Unit 5</option>
                                </select>
                            </div>

                            <div className="rounded-xl border-2 border-dashed border-gray-300 p-6 text-center hover:bg-gray-50 cursor-pointer transition-colors dark:border-white/10 dark:hover:bg-surface-800">
                                <File className="mx-auto h-8 w-8 text-gray-400" />
                                <p className="mt-2 text-sm text-gray-500 dark:text-gray-400">Click to browse or drag file here</p>
                                <p className="text-xs text-gray-400 mt-1">PDF, DOCX, JPG up to 10MB</p>
                            </div>

                            <button
                                type="submit"
                                disabled={isUploading}
                                className="w-full rounded-lg bg-primary-600 py-2.5 text-sm font-medium text-white hover:bg-primary-700 transition-colors disabled:opacity-50"
                            >
                                {isUploading ? 'Uploading...' : 'Upload File'}
                            </button>
                        </form>
                    </div>
                </div>
            )}
        </div>
    );
};

export default Notes;
