import { useState, useEffect } from 'react';
import { motion } from 'framer-motion';
import {
    Folder,
    FileText,
    Download,
    Search,
    Filter,
    Plus,
    ChevronRight,
    Home,
    FolderPlus,
    Upload
} from 'lucide-react';
import { useData } from '../context/DataContext';
import { useAuth } from '../context/AuthContext';

const Notes = () => {
    const { user } = useAuth();
    const {
        notes,
        folders,
        fetchNotesForFolder,
        fetchFoldersForParent,
        addFolder,
        addNote
    } = useData();

    const [currentFolderId, setCurrentFolderId] = useState<string | null>(null);
    const [folderPath, setFolderPath] = useState<{ id: string | null, name: string }[]>([
        { id: null, name: 'Home' }
    ]);

    const [searchQuery, setSearchQuery] = useState('');
    const [selectedCourse, setSelectedCourse] = useState('All');
    const [isCreateFolderOpen, setIsCreateFolderOpen] = useState(false);
    const [isUploadNoteOpen, setIsUploadNoteOpen] = useState(false);
    const [newFolderName, setNewFolderName] = useState('');

    // Upload Note State
    const [noteTitle, setNoteTitle] = useState('');
    const [noteFile, setNoteFile] = useState<File | null>(null);
    const [noteCourseId, setNoteCourseId] = useState('');

    useEffect(() => {
        loadContent(currentFolderId);
    }, [currentFolderId]);

    const loadContent = async (folderId: string | null) => {
        await Promise.all([
            fetchFoldersForParent(folderId),
            fetchNotesForFolder(folderId)
        ]);
    };

    const handleFolderClick = (folder: any) => {
        setCurrentFolderId(folder.id);
        setFolderPath([...folderPath, { id: folder.id, name: folder.name }]);
    };

    const handleBreadcrumbClick = (index: number) => {
        const newPath = folderPath.slice(0, index + 1);
        setFolderPath(newPath);
        setCurrentFolderId(newPath[newPath.length - 1].id);
    };

    const handleCreateFolder = async (e: React.FormEvent) => {
        e.preventDefault();
        if (!newFolderName.trim()) return;

        await addFolder(newFolderName, currentFolderId);
        setNewFolderName('');
        setIsCreateFolderOpen(false);
    };

    const handleUploadNote = async (e: React.FormEvent) => {
        e.preventDefault();
        if (!noteTitle.trim() || !noteFile) return;

        // In a real app, you'd upload the file to storage first and get the URL
        // For now, we'll mock the URL
        const mockUrl = URL.createObjectURL(noteFile);

        await addNote({
            id: '', // Generated by DB
            title: noteTitle,
            courseId: noteCourseId, // Should be selected from dropdown
            courseName: 'Selected Course', // Should be derived
            author: user?.name || 'Unknown',
            date: new Date().toISOString(),
            url: mockUrl,
            type: 'PDF', // Should be derived from file
            size: `${(noteFile.size / 1024 / 1024).toFixed(2)} MB`,
            folderId: currentFolderId
        });

        setNoteTitle('');
        setNoteFile(null);
        setIsUploadNoteOpen(false);
    };

    const container = {
        hidden: { opacity: 0 },
        show: {
            opacity: 1,
            transition: {
                staggerChildren: 0.05
            }
        }
    };

    const item = {
        hidden: { opacity: 0, y: 20 },
        show: { opacity: 1, y: 0 }
    };

    return (
        <div className="space-y-6">
            <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
                <div>
                    <h1 className="text-2xl font-bold text-surface-900">Study Notes</h1>
                    <p className="text-surface-500">Access and share study materials</p>
                </div>
                <div className="flex gap-2">
                    <button
                        onClick={() => setIsCreateFolderOpen(true)}
                        className="btn-secondary flex items-center gap-2"
                    >
                        <FolderPlus className="h-4 w-4" />
                        New Folder
                    </button>
                    <button
                        onClick={() => setIsUploadNoteOpen(true)}
                        className="btn-primary flex items-center gap-2"
                    >
                        <Upload className="h-4 w-4" />
                        Upload Note
                    </button>
                </div>
            </div>

            {/* Breadcrumbs */}
            <div className="flex items-center gap-2 text-sm text-surface-500 overflow-x-auto pb-2">
                {folderPath.map((crumb, index) => (
                    <div key={index} className="flex items-center gap-2 whitespace-nowrap">
                        {index > 0 && <ChevronRight className="h-4 w-4" />}
                        <button
                            onClick={() => handleBreadcrumbClick(index)}
                            className={`hover:text-primary-600 flex items-center gap-1 ${index === folderPath.length - 1 ? 'font-semibold text-surface-900' : ''
                                }`}
                        >
                            {index === 0 && <Home className="h-4 w-4" />}
                            {crumb.name}
                        </button>
                    </div>
                ))}
            </div>

            {/* Content Grid */}
            <motion.div
                variants={container}
                initial="hidden"
                animate="show"
                className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-4"
            >
                {/* Folders */}
                {folders.map((folder) => (
                    <motion.div
                        key={folder.id}
                        variants={item}
                        onClick={() => handleFolderClick(folder)}
                        className="group p-4 bg-white rounded-xl border border-surface-200 hover:border-primary-300 hover:shadow-md transition-all cursor-pointer"
                    >
                        <div className="flex items-start justify-between mb-3">
                            <div className="p-2 bg-yellow-50 text-yellow-600 rounded-lg group-hover:bg-yellow-100 transition-colors">
                                <Folder className="h-6 w-6 fill-current" />
                            </div>
                        </div>
                        <h3 className="font-semibold text-surface-900 truncate">{folder.name}</h3>
                        <p className="text-xs text-surface-500 mt-1">Folder</p>
                    </motion.div>
                ))}

                {/* Notes */}
                {notes.map((note) => (
                    <motion.div
                        key={note.id}
                        variants={item}
                        className="group p-4 bg-white rounded-xl border border-surface-200 hover:border-primary-300 hover:shadow-md transition-all"
                    >
                        <div className="flex items-start justify-between mb-3">
                            <div className="p-2 bg-primary-50 text-primary-600 rounded-lg group-hover:bg-primary-100 transition-colors">
                                <FileText className="h-6 w-6" />
                            </div>
                            <button className="p-1.5 text-surface-400 hover:text-primary-600 hover:bg-primary-50 rounded-lg transition-colors">
                                <Download className="h-4 w-4" />
                            </button>
                        </div>
                        <h3 className="font-semibold text-surface-900 truncate mb-1">{note.title}</h3>
                        <div className="flex items-center gap-2 text-xs text-surface-500 mb-3">
                            <span className="bg-surface-100 px-2 py-0.5 rounded">{note.type}</span>
                            <span>{note.size}</span>
                        </div>
                        <div className="flex items-center justify-between text-xs text-surface-400 border-t border-surface-100 pt-3">
                            <span>{new Date(note.date).toLocaleDateString()}</span>
                            <span>{note.author}</span>
                        </div>
                    </motion.div>
                ))}

                {folders.length === 0 && notes.length === 0 && (
                    <div className="col-span-full py-12 text-center text-surface-500">
                        <Folder className="h-12 w-12 mx-auto mb-3 text-surface-300" />
                        <p>This folder is empty</p>
                    </div>
                )}
            </motion.div>

            {/* Create Folder Modal */}
            {isCreateFolderOpen && (
                <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 backdrop-blur-sm p-4">
                    <div className="bg-white rounded-xl shadow-xl w-full max-w-md p-6">
                        <h2 className="text-xl font-bold mb-4">Create New Folder</h2>
                        <form onSubmit={handleCreateFolder}>
                            <input
                                type="text"
                                value={newFolderName}
                                onChange={(e) => setNewFolderName(e.target.value)}
                                placeholder="Folder Name"
                                className="w-full p-2 border border-surface-300 rounded-lg mb-4 focus:ring-2 focus:ring-primary-500 outline-none"
                                autoFocus
                            />
                            <div className="flex justify-end gap-2">
                                <button
                                    type="button"
                                    onClick={() => setIsCreateFolderOpen(false)}
                                    className="px-4 py-2 text-surface-600 hover:bg-surface-100 rounded-lg"
                                >
                                    Cancel
                                </button>
                                <button
                                    type="submit"
                                    className="px-4 py-2 bg-primary-600 text-white rounded-lg hover:bg-primary-700"
                                >
                                    Create
                                </button>
                            </div>
                        </form>
                    </div>
                </div>
            )}

            {/* Upload Note Modal */}
            {isUploadNoteOpen && (
                <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 backdrop-blur-sm p-4">
                    <div className="bg-white rounded-xl shadow-xl w-full max-w-md p-6">
                        <h2 className="text-xl font-bold mb-4">Upload Note</h2>
                        <form onSubmit={handleUploadNote} className="space-y-4">
                            <div>
                                <label className="block text-sm font-medium text-surface-700 mb-1">Title</label>
                                <input
                                    type="text"
                                    value={noteTitle}
                                    onChange={(e) => setNoteTitle(e.target.value)}
                                    className="w-full p-2 border border-surface-300 rounded-lg focus:ring-2 focus:ring-primary-500 outline-none"
                                    required
                                />
                            </div>
                            <div>
                                <label className="block text-sm font-medium text-surface-700 mb-1">File</label>
                                <input
                                    type="file"
                                    onChange={(e) => setNoteFile(e.target.files?.[0] || null)}
                                    className="w-full p-2 border border-surface-300 rounded-lg focus:ring-2 focus:ring-primary-500 outline-none"
                                    required
                                />
                            </div>
                            <div className="flex justify-end gap-2 pt-2">
                                <button
                                    type="button"
                                    onClick={() => setIsUploadNoteOpen(false)}
                                    className="px-4 py-2 text-surface-600 hover:bg-surface-100 rounded-lg"
                                >
                                    Cancel
                                </button>
                                <button
                                    type="submit"
                                    className="px-4 py-2 bg-primary-600 text-white rounded-lg hover:bg-primary-700"
                                >
                                    Upload
                                </button>
                            </div>
                        </form>
                    </div>
                </div>
            )}
        </div>
    );
};

export default Notes;
