import { useState } from 'react';
import { motion } from 'framer-motion';
import {
    Calendar,
    Clock,
    MapPin,
    Users,
    Plus,
    Search,
    User
} from 'lucide-react';
import { useData } from '../context/DataContext';
import { useAuth } from '../context/AuthContext';

const Practicals = () => {
    const { user } = useAuth();
    const { practicals, addPractical, updateUserGroup } = useData();
    const [isCreateOpen, setIsCreateOpen] = useState(false);
    const [isAssignGroupOpen, setIsAssignGroupOpen] = useState(false);

    // Form States
    const [newPractical, setNewPractical] = useState({
        subject: '',
        title: '',
        group: 'J1',
        date: '',
        time: '',
        room: ''
    });

    const [assignGroup, setAssignGroup] = useState({
        userId: '', // In real app, this would be a search/select
        group: 'J1'
    });

    const handleCreatePractical = async (e: React.FormEvent) => {
        e.preventDefault();
        await addPractical({
            id: '', // Generated by DB
            ...newPractical
        } as any);
        setIsCreateOpen(false);
        setNewPractical({ subject: '', title: '', group: 'J1', date: '', time: '', room: '' });
    };

    const handleAssignGroup = async (e: React.FormEvent) => {
        e.preventDefault();
        await updateUserGroup(assignGroup.userId, assignGroup.group);
        setIsAssignGroupOpen(false);
        setAssignGroup({ userId: '', group: 'J1' });
    };

    const container = {
        hidden: { opacity: 0 },
        show: {
            opacity: 1,
            transition: {
                staggerChildren: 0.1
            }
        }
    };

    const item = {
        hidden: { opacity: 0, y: 20 },
        show: { opacity: 1, y: 0 }
    };

    return (
        <div className="space-y-6">
            <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
                <div>
                    <h1 className="text-2xl font-bold text-surface-900">Practical Schedule</h1>
                    <p className="text-surface-500">
                        {user?.role === 'admin'
                            ? 'Manage practical sessions and groups'
                            : `Viewing schedule for Group ${user?.practicalGroup || 'Unassigned'}`}
                    </p>
                </div>
                {user?.role === 'admin' && (
                    <div className="flex gap-2">
                        <button
                            onClick={() => setIsAssignGroupOpen(true)}
                            className="btn-secondary flex items-center gap-2"
                        >
                            <Users className="h-4 w-4" />
                            Assign Group
                        </button>
                        <button
                            onClick={() => setIsCreateOpen(true)}
                            className="btn-primary flex items-center gap-2"
                        >
                            <Plus className="h-4 w-4" />
                            Add Practical
                        </button>
                    </div>
                )}
            </div>

            <motion.div
                variants={container}
                initial="hidden"
                animate="show"
                className="grid gap-4"
            >
                {practicals.length > 0 ? (
                    practicals.map((practical) => (
                        <motion.div
                            key={practical.id}
                            variants={item}
                            className="card-clean p-4 flex flex-col sm:flex-row sm:items-center justify-between gap-4"
                        >
                            <div className="flex items-start gap-4">
                                <div className="h-12 w-12 rounded-lg bg-accent-50 text-accent-600 flex items-center justify-center border border-accent-100 shrink-0">
                                    <Calendar className="h-6 w-6" />
                                </div>
                                <div>
                                    <div className="flex items-center gap-2 mb-1">
                                        <h3 className="font-semibold text-surface-900">{practical.subject}</h3>
                                        <span className="text-xs font-medium px-2 py-0.5 rounded bg-surface-100 text-surface-600">
                                            Group {practical.group}
                                        </span>
                                    </div>
                                    <p className="text-sm text-surface-500">{practical.title}</p>
                                </div>
                            </div>

                            <div className="flex flex-wrap items-center gap-4 text-sm text-surface-500">
                                <div className="flex items-center gap-2 bg-surface-50 px-3 py-1.5 rounded-lg">
                                    <Clock className="h-4 w-4" />
                                    <span>{practical.time}</span>
                                </div>
                                <div className="flex items-center gap-2 bg-surface-50 px-3 py-1.5 rounded-lg">
                                    <MapPin className="h-4 w-4" />
                                    <span>{practical.room}</span>
                                </div>
                                <div className="flex items-center gap-2 bg-surface-50 px-3 py-1.5 rounded-lg">
                                    <Calendar className="h-4 w-4" />
                                    <span>{new Date(practical.date).toLocaleDateString()}</span>
                                </div>
                            </div>
                        </motion.div>
                    ))
                ) : (
                    <div className="text-center py-12 text-surface-500 bg-white rounded-xl border border-surface-200">
                        <Calendar className="h-12 w-12 mx-auto mb-3 text-surface-300" />
                        <p>No practicals scheduled for your group.</p>
                    </div>
                )}
            </motion.div>

            {/* Create Practical Modal */}
            {isCreateOpen && (
                <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 backdrop-blur-sm p-4">
                    <div className="bg-white rounded-xl shadow-xl w-full max-w-md p-6">
                        <h2 className="text-xl font-bold mb-4">Schedule Practical</h2>
                        <form onSubmit={handleCreatePractical} className="space-y-4">
                            <div>
                                <label className="block text-sm font-medium text-surface-700 mb-1">Subject</label>
                                <input
                                    type="text"
                                    value={newPractical.subject}
                                    onChange={(e) => setNewPractical({ ...newPractical, subject: e.target.value })}
                                    className="w-full p-2 border border-surface-300 rounded-lg focus:ring-2 focus:ring-primary-500 outline-none"
                                    required
                                />
                            </div>
                            <div>
                                <label className="block text-sm font-medium text-surface-700 mb-1">Title/Topic</label>
                                <input
                                    type="text"
                                    value={newPractical.title}
                                    onChange={(e) => setNewPractical({ ...newPractical, title: e.target.value })}
                                    className="w-full p-2 border border-surface-300 rounded-lg focus:ring-2 focus:ring-primary-500 outline-none"
                                    required
                                />
                            </div>
                            <div className="grid grid-cols-2 gap-4">
                                <div>
                                    <label className="block text-sm font-medium text-surface-700 mb-1">Group</label>
                                    <select
                                        value={newPractical.group}
                                        onChange={(e) => setNewPractical({ ...newPractical, group: e.target.value })}
                                        className="w-full p-2 border border-surface-300 rounded-lg focus:ring-2 focus:ring-primary-500 outline-none"
                                    >
                                        <option value="J1">J1</option>
                                        <option value="J2">J2</option>
                                        <option value="J3">J3</option>
                                    </select>
                                </div>
                                <div>
                                    <label className="block text-sm font-medium text-surface-700 mb-1">Room</label>
                                    <input
                                        type="text"
                                        value={newPractical.room}
                                        onChange={(e) => setNewPractical({ ...newPractical, room: e.target.value })}
                                        className="w-full p-2 border border-surface-300 rounded-lg focus:ring-2 focus:ring-primary-500 outline-none"
                                        required
                                    />
                                </div>
                            </div>
                            <div className="grid grid-cols-2 gap-4">
                                <div>
                                    <label className="block text-sm font-medium text-surface-700 mb-1">Date</label>
                                    <input
                                        type="date"
                                        value={newPractical.date}
                                        onChange={(e) => setNewPractical({ ...newPractical, date: e.target.value })}
                                        className="w-full p-2 border border-surface-300 rounded-lg focus:ring-2 focus:ring-primary-500 outline-none"
                                        required
                                    />
                                </div>
                                <div>
                                    <label className="block text-sm font-medium text-surface-700 mb-1">Time</label>
                                    <input
                                        type="time"
                                        value={newPractical.time}
                                        onChange={(e) => setNewPractical({ ...newPractical, time: e.target.value })}
                                        className="w-full p-2 border border-surface-300 rounded-lg focus:ring-2 focus:ring-primary-500 outline-none"
                                        required
                                    />
                                </div>
                            </div>
                            <div className="flex justify-end gap-2 pt-2">
                                <button
                                    type="button"
                                    onClick={() => setIsCreateOpen(false)}
                                    className="px-4 py-2 text-surface-600 hover:bg-surface-100 rounded-lg"
                                >
                                    Cancel
                                </button>
                                <button
                                    type="submit"
                                    className="px-4 py-2 bg-primary-600 text-white rounded-lg hover:bg-primary-700"
                                >
                                    Schedule
                                </button>
                            </div>
                        </form>
                    </div>
                </div>
            )}

            {/* Assign Group Modal */}
            {isAssignGroupOpen && (
                <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 backdrop-blur-sm p-4">
                    <div className="bg-white rounded-xl shadow-xl w-full max-w-md p-6">
                        <h2 className="text-xl font-bold mb-4">Assign Student Group</h2>
                        <form onSubmit={handleAssignGroup} className="space-y-4">
                            <div>
                                <label className="block text-sm font-medium text-surface-700 mb-1">Student ID (UUID)</label>
                                <input
                                    type="text"
                                    value={assignGroup.userId}
                                    onChange={(e) => setAssignGroup({ ...assignGroup, userId: e.target.value })}
                                    placeholder="Enter Student UUID"
                                    className="w-full p-2 border border-surface-300 rounded-lg focus:ring-2 focus:ring-primary-500 outline-none"
                                    required
                                />
                                <p className="text-xs text-surface-500 mt-1">In a real app, this would be a user search.</p>
                            </div>
                            <div>
                                <label className="block text-sm font-medium text-surface-700 mb-1">Group</label>
                                <select
                                    value={assignGroup.group}
                                    onChange={(e) => setAssignGroup({ ...assignGroup, group: e.target.value })}
                                    className="w-full p-2 border border-surface-300 rounded-lg focus:ring-2 focus:ring-primary-500 outline-none"
                                >
                                    <option value="J1">J1</option>
                                    <option value="J2">J2</option>
                                    <option value="J3">J3</option>
                                </select>
                            </div>
                            <div className="flex justify-end gap-2 pt-2">
                                <button
                                    type="button"
                                    onClick={() => setIsAssignGroupOpen(false)}
                                    className="px-4 py-2 text-surface-600 hover:bg-surface-100 rounded-lg"
                                >
                                    Cancel
                                </button>
                                <button
                                    type="submit"
                                    className="px-4 py-2 bg-primary-600 text-white rounded-lg hover:bg-primary-700"
                                >
                                    Assign
                                </button>
                            </div>
                        </form>
                    </div>
                </div>
            )}
        </div>
    );
};

export default Practicals;
